### ISSUE TITLE
Error test matrix-js-sdk sync-browserify.spec.js

### ISSUE THREAD

**Issue by dCarmonaArboleda** [matrix-org/matrix-js-sdk#1389]
When running the matrix-js-sdk tests, I get an error in the Browserify Test from the `spec / browserify / sync-browserify.spec.js` file

happens when cloning the project and running the tests

` FAIL  spec/browserify/sync-browserify.spec.js (45.058s)
  Browserify Test
    ✕ Sync (39294ms)

  ● Browserify Test › Sync

    : Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:

      68 |     });
      69 | 
    > 70 |     it("Sync", async function() {
         |     ^
      71 |         const event = utils.mkMembership({
      72 |             room: ROOM_ID,
      73 |             mship: "join",

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (spec/browserify/sync-browserify.spec.js:70:5)
      at Object.<anonymous> (spec/browserify/sync-browserify.spec.js:33:1)
`

**Comment by turt2live** [comment]
Yea, it's a bit flakey. If you keep retrying it it'll probably go away.
