### ISSUE TITLE
M_UNKNOWN: No known servers when joining a room - when upgrading to 9.4.1

### ISSUE THREAD

**Issue by Tbaut** [matrix-org/matrix-js-sdk#1575]
**Describe the bug**
My matrix bot worked well with v9.1.0, and I recently upgraded to 9.4.1.
I now have an error appearing when I launch the bot, although everything seem to keep working.
The error appears in the `bot.joinRoom` method.

I have no clue where it could come from. Any pointer would be greatly appreciated.

**To Reproduce**
Using the following:
```js
import * as mSDK from 'matrix-js-sdk';

const bot = mSDK.createClient({
  accessToken,
  baseUrl: 'https://matrix.org',
  localTimeoutMs: 10000,
  userId: botUserId
});

bot.on('RoomMember.membership', (_, member: Record<string, string>) => {
  if (member.membership === 'invite' && member.userId === botUserId) {
    bot.joinRoom(member.roomId).then(() => {
      logger.info(`Auto-joined ${member.roomId}.`);
    }).catch((e) => logger.error('Auto-join error', e));
  }
});

bot.startClient({ initialSyncLimit: 0 }).catch((e) => logger.error(e));
```

**Expected behavior**
No error

**Error dump**
```bash
[ERROR] default - Auto-join error M_UNKNOWN: No known servers
    at parseErrorResponse (/bot/node_modules/matrix-js-sdk/lib/http-api.js:826:13)
    at /bot/node_modules/matrix-js-sdk/lib/http-api.js:781:17
    at Request._callback (/bot/node_modules/matrix-js-sdk/lib/http-api.js:715:9)
    at Request.self.callback (/bot/node_modules/request/request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.<anonymous> (/bot/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:376:20)
    at IncomingMessage.<anonymous> (/bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:482:28)
    at IncomingMessage.emit (node:events:388:22) {
  errcode: 'M_UNKNOWN',
  data: { errcode: 'M_UNKNOWN', error: 'No known servers' },
  httpStatus: 404
}
```

Node.js: v12.14.1

**Comment by dimitri-bourreau** [comment]
If this can help (if anyone is on this...) I have the same issue when leaving a room (rejecting an invite).

**Comment by byanes** [comment]
Same issue here. I invite someone to a room (1:1), I leave the room before the other person accepts the invite, and when the other person tries to join I get the error: 

```
data: {errcode: 'M_UNKNOWN', error: 'No known servers'}
errcode: "M_UNKNOWN"
httpStatus: 404
message: "No known servers"
name: "M_UNKNOWN"
```
Any ideas?
