### ISSUE TITLE
syntaxerror: cannot use import statement outside a module nodejs

### ISSUE THREAD

**Issue by wubigo** [matrix-org/matrix-js-sdk#1867]
**Describe the bug**
ubuntu@ip-172-31-44-135:~/matrix-js-sdk/examples/node$ node app
/home/ubuntu/matrix-js-sdk/src/index.ts:17
import * as matrixcs from "./matrix";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/ubuntu/matrix-js-sdk/examples/node/app.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
ubuntu@ip-172-31-44-135:~/matrix-js-sdk/examples/node$ node -v
v14.17.5

**To Reproduce**
1. git clone https://github.com/matrix-org/matrix-js-sdk.git
2. cd matrix-js-sdk/examples/node
3. npm install 
4. node app

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wubigo** [comment]
use package instead
