### ISSUE TITLE
Error uploading one-time keys TypeError: account.unpublished_fallback_key is not a function

### ISSUE THREAD

**Issue by nahakiole** [matrix-org/matrix-js-sdk#2092]
**Describe the bug**
A undocumented error called `Error uploading one-time keys TypeError: account.unpublished_fallback_key is not a function` is printed in the console, when using loginWithPassword or using an access token to login.

**To Reproduce**
1. Setup matrix-js-sdk for Encryption
2. Try to login via password and username
```js
this.client.loginWithPassword(username, password, (err, res) => {
    this.client.initCrypto().then(() => {
        this.client.startClient({});
    })
});
```
```
logger.js:57 Error uploading one-time keys TypeError: account.unpublished_fallback_key is not a function
    at http://localhost:4200/vendor.js:61196:39
    at http://localhost:4200/vendor.js:60952:9
    at LocalStorageCryptoStore.getAccount (http://localhost:4200/vendor.js:74620:5)
    at OlmDevice.getAccount (http://localhost:4200/vendor.js:60947:22)
    at http://localhost:4200/vendor.js:61195:16
    at LocalStorageCryptoStore.doTxn (http://localhost:4200/vendor.js:74646:28)
    at http://localhost:4200/vendor.js:61194:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:4200/vendor.js:107143:24)
    at _next (http://localhost:4200/vendor.js:107165:9)
```

**Expected behavior**
I would expect the encryption to work and be better documented? It's not clear how I could add/generate key according to the implementation guide after logging in, similar to the element client, where you can import keys after logging in.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 96.0.4664.110

**Comment by t3chguy** [comment]
Update to latest olm.

**Comment by nahakiole** [comment]
I'm using the one specified in the readme:

> yarn add https://packages.matrix.org/npm/olm/olm-3.1.4.tgz (replace the URL with the latest version you want to use from https://packages.matrix.org/npm/olm/)
> global.Olm = require('olm'); before loading matrix-js-sdk.

So I should be using 3.2.1? If so I can create a pull request updating the readme.

**Comment by nahakiole** [comment]
I'm now using 3.2.1 and I still get the same error.

**Comment by t3chguy** [comment]
https://gitlab.matrix.org/matrix-org/olm/-/releases goes up higher

**Comment by xRealNeon** [comment]
How do I use the newer one? I have the same issue.

**Comment by xRealNeon** [comment]
Found it https://gitlab.matrix.org/matrix-org/olm/-/packages/50

**Comment by menturion** [comment]
You can use the `olm.wasm` from the latest `element-web` build (https://github.com/vector-im/element-web/releases/tag/v1.9.9-rc.1, asset: element-v1.9.9-rc.1.tar.gz -> see file `olm.cccfd1d.wasm`).
