### ISSUE TITLE
MatrixClient throwing error upon completing verification

### ISSUE THREAD

**Issue by MangoCubes** [matrix-org/matrix-js-sdk#2276]
**Describe the bug**
I am currently trying to implement a bot that, upon encountering an unverified session, the bot sends verification request to the user immediately, and does SAS verification via console. However, upon completing the verification, Error: No getCrossSigningKey callback supplied error is thrown, and from the user's (the one who is trying to verify against a bot) point of view, the verification seems to be cancelled. However, the server sometimes considers this verification done, and sometimes, not. I cannot determine what decides the outcome. This occurs when the server sends verification. Such bug does not happen if the client sends the verification request to the server first.

**To Reproduce**
This is the code I am using to verify a user upon encountering an unverified session. The lack of implementation regarding verification makes writing code rather tricky.
```typescript
	async sendVerification(userId: string){ //Upon detecting unverified sessions, the target's user ID is called with this function
		const req = await this.client.requestVerification(userId); //Send verification
		await req.waitFor(() => req.started || req.cancelled); //Wait until it is cancelled or accepted
		if (req.cancelled) this.logMessage('Verification cancelled by user.');
		else await this.verificationHandler(req);
	}

	async verificationHandler(req: VerificationRequest){ //This is also used upon receiving a verification request initiated by the other party
		if (!req.verifier) {
			if (!req.initiatedByMe) {
				req.beginKeyVerification(verificationMethods.SAS);
				await req.accept(); //Accept if not started by us
			} else await req.waitFor(() => req.started || req.cancelled);
			if (req.cancelled) {
				await this.logMessage('Verification cancelled.');
				return;
			}
		}
		
		req.verifier.once(SasEvent.ShowSas, async (e: ISasEvent) => { //When it is time to show SAS
			if (e.sas.decimal) console.log(`Decimal: ${e.sas.decimal.join(', ')}`);
			if (e.sas.emoji){
				let emojis = [];
				for(const emoji of e.sas.emoji) emojis.push(`${emoji[0]} (${emoji[1]})`);
				console.log(`Emojis: ${emojis.join(', ')}`);
			}
			const rl = readline.createInterface({
				input: process.stdin,
				output: process.stdout
			});
			rl.setPrompt('Do the emojis/decimals match? (c: Cancel) [y/n/c]: '); //Ask on console whether emojis match or not
			rl.prompt();
			rl.on('line', async (line) => {
				switch(line.trim().toLowerCase()) {
					case 'y':
						e.confirm();
						console.log('Verified. Please wait until the peer verifies their emoji.');
						rl.close();
						return;
					case 'n':
						e.mismatch();
						console.log('Emojis do not match; Communication may be compromised.');
						rl.close();
						return;
					case 'c':
						e.cancel();
						console.log('Verification cancelled.');
						rl.close();
						return;
				}
				rl.prompt();
			});
		});
		try{
			await req.verifier.verify(); //Start SAS verification, this is where error is thrown
			this.logMessage('Verification successful.');
		} catch(e){
			this.logMessage('Verification cancelled.');
			this.logMessage(e); //This is where the error gets printed
			return;
		}
	}
```

**Expected behavior**
I expect the verification to go through. After all, the error is thrown AFTER both clients confirm that the SAS match.

**Screenshots**
Here is the error message, and some logs around it (the logger is enabled):
```
# This message just below is printed upon both side confirming that the SAS match.
SAS calculateMAC: hkdf-hmac-sha256 [
  'ed25519:/lsb****/f***************pYr56kkIbY5xTxSusM,ed25519:IFN*****MH',
  'MATRIX_KEY_VERIFICATION_MAC@guest:example.comIFN*****MH@bot:example.comTHS*****JXCBSQcwd**********bSZ8PrsIf3wv209KEY_IDS'
] /9H*****ZlF/b***************bGxyVmxwa2JHeHk
SAS calculateMAC: hkdf-hmac-sha256 [
  '8Gn/IwpOiq0Ioo***************lCFObHWyK7n8BY',
  'MATRIX_KEY_VERIFICATION_MAC@guest:example.comIFN*****MH@bot:example.comTHS*****JXCBSQcwd**********bSZ8PrsIf3wv209ed25519:IFN*****MH'
] lREZWhFxRnjKbmpLYm1wTFltMXdURmx0TVhkVVJteDA
SAS calculateMAC: hkdf-hmac-sha256 [
  '/lsb****/f***************pYr56kkIbY5xTxSusM',
  'MATRIX_KEY_VERIFICATION_MAC@guest:example.comIFN*****MH@bot:example.comTHS*****JXCBSQcwd**********bSZ8PrsIf3wv209ed25519:/lsb****/f***************pYr56kkIbY5xTxSusM'
] ANw5NS9BOUJ***************dXVlpzVm5kWFZscHo
Verification completed! Marking devices verified:  [ 'IFN*****MH', '/lsb****/f***************pYr56kkIbY5xTxSusM' ]
Master key /lsb****/f***************pYr56kkIbY5xTxSusM for @guest:example.com marked verified. Signing...
PUT /sendToDevice/m.key.verification.cancel/m1649171451816.6 { '@guest:example.com': [ 'IFN*****MH' ] }
Verification cancelled.
Error: No getCrossSigningKey callback supplied
    at CrossSigningInfo.getCrossSigningKey (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/CrossSigning.js:110:13)
    at CrossSigningInfo.signObject (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/CrossSigning.js:486:42)
    at CrossSigningInfo.signUser (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/CrossSigning.js:503:17)
    at Crypto.setDeviceVerification (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/index.js:1976:52)
    at MatrixClient.setDeviceVerification (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/client.js:1160:23)
    at MatrixClient.setDeviceVerified (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/client.js:1106:23)
    at SAS.verifyKeys (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/verification/Base.js:374:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SAS.checkMAC (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/verification/SAS.js:463:5)
    at async SAS.doRespondVerification (/workspace/projects/matrix-bot-ts/node_modules/matrix-js-sdk/lib/crypto/verification/SAS.js:428:7)
Saving device tracking data s615_****_32_***_630_1_1359_182_1
```
I am willing to show the censored parts if it is necessary.
What makes this rather odd for me is that the logger prints `Verification completed! Marking devices verified`, and it fails.

On the client's side, the following message is shown:
`bot cancelled verification. Start verification again from their profile.`

The browser console prints the following:
`Error: Other side cancelled verification because Error: No getCrossSigningKey callback supplied (m.unknown)`

**Desktop (please complete the following information):**
 - OS: [HamoniKR]
 - Browser [Chromium]
 - Version [91.0.4472.101]

**Server (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Node.js server

**Additional context**
This happens when the server is running, and a new session of an existing account is detected. Verification seems to work well when the client sends the verification request to the server, but not the other way around.

I genuinely cannot find any documentation regarding verification implementation, nor the fix for this particular error. All I get is the part of the source code that prints the error message in the title. Any help would be appreciated. Thank you.

Edit 3: Apparently the error is thrown because `CrossSigningInfo`'s `callbacks.getCrossSigningKey` is missing. 
https://github.com/matrix-org/matrix-js-sdk/blob/12e525b664ad8d1ad5d57fc322a0a9f247af52a2/src/crypto/CrossSigning.ts#L113
However, when I decided to comment that error throwing part out, it worked just fine. It called this line successfully, and the verification went through without errors by calling `cacheCallbacks.getCrossSigningKeyCache` instead.
https://github.com/matrix-org/matrix-js-sdk/blob/12e525b664ad8d1ad5d57fc322a0a9f247af52a2/src/crypto/CrossSigning.ts#L132

As a result, changing this line
https://github.com/matrix-org/matrix-js-sdk/blob/12e525b664ad8d1ad5d57fc322a0a9f247af52a2/src/crypto/CrossSigning.ts#L112
to
`if (!shouldCache && !this.callbacks.getCrossSigningKey) {`
makes it work. However, I would like to see the proper way of handling the verification.

**Comment by MangoCubes** [comment]
I have edited the original issue because I was missing some key info: Verification looks like it worked (ie server does not treat as verified after this) on the first time with no error outputs, and any further verifications shows the error message above. I'm guessing the error is thrown because the device server is verifying never expected to receive verification again. But now the issue is figuring out why the server is not treating the device as verified in the first attempt, despite not having any errors. I have tested it against official Matrix server, and the result is same: First verification goes through with no errors, server still treats device as unverified, completing additional verification prints that error.

**Comment by nitesh-habilelabs** [comment]
hi, is there any update on this issue?
i am trying to integrate matrix into my react-native app using matrix-js-sdk and @matrix-org/olm. 
i am getting this error “No getCrossSigningKey callback supplied” . 
i am trying cross signing and decryption of messages.
thank you in advance.

**Comment by richvdh** [comment]
the crypto stack has been rewritten since this issue was opened. If it's still a problem with Rust Crypto, please open a new issue.
