### ISSUE TITLE
Node app fails to pull in olm.wasm

### ISSUE THREAD

**Issue by san1t1** [matrix-org/matrix-js-sdk#2764]
Package.json (edited for brevity)
```json
{
    "dependencies": {
        "@excession/system-utils": "4.16.4",
        "@matrix-org/olm": "https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.13.tgz",
        "cross-fetch": "3.1.5",
        "matrix-bot-sdk": "0.6.2",
    },
    "devDependencies": {
        
        "matrix-js-sdk": "20.1.0",
        "msw": "0.39.2",
        "prettier": "2.7.1",
        "request": "2.88.2"
    }
}
```
SDK use (again, edited)
```js
global.Olm = require('olm');
const matrix = require('matrix-js-sdk');
const request = require('request');
// ...

this.#client = matrix.createClient({
                baseUrl: homeServerUrl,
                deviceId,
                userId,
                accessToken,
                sessionStore: new matrix.MemoryStore(),
                cryptoStore: new matrix.MemoryCryptoStore(),
                request,
            });
 await this.#client.initCrypto();            
```
Error, thrown by `node-fetch`
```
 TypeError: Only absolute URLs are supported

      at getNodeRequestOptions (node_modules/node-fetch/lib/index.js:1327:9)
      at node_modules/node-fetch/lib/index.js:1440:19
      at Function.fetch (node_modules/node-fetch/lib/index.js:1437:9)
      at Function.fetch (node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
      at node_modules/jest-fetch-mock/src/index.js:114:18
      at node_modules/olm/olm.js:34:222
      at node_modules/olm/olm.js:34:445
      at node_modules/olm/olm.js:34:468
      at node_modules/olm/olm.js:140:9
      at Object.<anonymous>.olm_exports.init (node_modules/olm/olm.js:133:22)
      at Crypto.init (node_modules/matrix-js-sdk/src/crypto/index.ts:461:26)
```
This is offensive because it's being passed this URL structure:
```js
 {
      parsedURL: Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: null,
        query: null,
        pathname: '/home/user/matrix-bridge/node_modules/olm/olm.wasm',
        path: '/home/user/matrix-bridge/node_modules/olm/olm.wasm',
        href: '/home/user/matrix-bridge/node_modules/olm/olm.wasm'
      }
    }
```

Which is validated against this:
```js
       if (!parsedURL.protocol || !parsedURL.hostname) {
		throw new TypeError('Only absolute URLs are supported');
	}

	if (!/^https?:$/.test(parsedURL.protocol)) {
		throw new TypeError('Only HTTP(S) protocols are supported');
	}
```

**Comment by t3chguy** [comment]
This is due to Node 18 incompatibility. The next release of matrix-js-sdk will support Node 18. For now I suggest using Node 16 as it is still the target LTS release.

**Comment by san1t1** [comment]
Suggest you include an engines block in your `package.json` so that you can prevent unsupported upgrades.

**Comment by t3chguy** [comment]
Yup, the issue was noticed & fixed within a single release cycle so it wasn't possible to add such a restriction.
