### ISSUE TITLE
SAS verification › verification › should verify a cross-signing key: is flakey

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-js-sdk#2802]
```

SAS verification › verification › should verify a cross-signing key: spec/unit/crypto/verification/sas.spec.ts#L352
thrown: "Exceeded timeout of 5000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

    at it (spec/unit/crypto/verification/sas.spec.ts:352:9)
    at describe (spec/unit/crypto/verification/sas.spec.ts:78:5)
    at Object.describe (spec/unit/crypto/verification/sas.spec.ts:37:1)

```

On https://github.com/matrix-org/matrix-js-sdk/actions/runs/3321027102

**Comment by richvdh** [comment]
seems like this hasn't been seen for a while, so I'm going to go ahead and close it
