### ISSUE TITLE
Fetch not found using ts-node 

### ISSUE THREAD

**Issue by selankon** [matrix-org/matrix-js-sdk#2905]
With:

```
➜ node -v           
v18.12.1
```

When I use `npm run dev` on my program, under the hood doing `npx ts-node src/index.ts`, I got this error for any simple configuration:

```
Can't fetch server versions, continuing to initialise sync, this will be retried later ConnectionError: fetch failed: global.fetch is not a function
    at MatrixHttpApi.requestOtherUrl (/home/user/project/node_modules/matrix-js-sdk/src/http-api/fetch.ts:294:19)
    at MatrixHttpApi.request (/home/user/project/node_modules/matrix-js-sdk/src/http-api/fetch.ts:213:21)
    at MatrixClient.getVersions (/home/user/project/node_modules/matrix-js-sdk/src/client.ts:6722:48)
    at MatrixClient.startClient (/home/user/project/node_modules/matrix-js-sdk/src/client.ts:1197:24)
    at new MatrixorgWrapper (/home/user/project/src/lib/matrixorg-wrapper.ts:24:21)
    at startDbService (/home/user/project/src/services/db.ts:27:28)
    at Object.<anonymous> (/home/user/project/src/index.ts:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module.m._compile (/home/user/project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
```

It seems that for some reason typescript can't find the wrapped fetch implementation on node 18, and I can't find any workaround to fix this. 

Does anyone "fetched" this problem? Probably is a miss-configuration of TS, here my `tsconfig.json`.

```json
{
  "compilerOptions": {
    "target": "es2021",           // Originally was  es2016
    "lib":  ["es2021", "dom"], // Added by me
    "module": "commonjs",
    "outDir": "./dist",
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true 
  }
}
```

**Comment by selankon** [comment]
Anyway, I found a solution installing  the external `"cross-fetch": "^3.1.5",` library and passing it to the client as `fetchFn`

**Comment by t3chguy** [comment]
Yeah passing a `fetchFn` if your environment doesn't natively support it is the suggestion I was about to give

**Comment by selankon** [comment]
I don't know why this happen but with the fix I gave seems to work
