### ISSUE TITLE
Can't sync, expected UserID string to start with '@'

### ISSUE THREAD

**Issue by selankon** [matrix-org/matrix-js-sdk#2909]
Hi,

Using `"matrix-js-sdk": "^21.1.0",`
And

```
➜ node -v           
v18.12.1
``` 

I'm trying to sync and I get this strange error:

```
Getting filter failed M_INVALID_PARAM: MatrixError: [400] Expected UserID string to start with '@' (https://matrix.org/_matrix/client/r0/user/$userId/filter)
    at parseErrorResponse (/home/bolet/Z_LINKS/proyectosGit/LoRaTRUST/LoRaTRUST-JsBackend/node_modules/matrix-js-sdk/src/http-api/utils.ts:83:16)
    at MatrixHttpApi.requestOtherUrl (/home/bolet/Z_LINKS/proyectosGit/LoRaTRUST/LoRaTRUST-JsBackend/node_modules/matrix-js-sdk/src/http-api/fetch.ts:300:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  httpStatus: 400,
  url: 'https://matrix.org/_matrix/client/r0/user/$userId/filter',
  event: undefined,
  errcode: 'M_INVALID_PARAM',
  data: {
    errcode: 'M_INVALID_PARAM',
    error: "Expected UserID string to start with '@'"
  }
}
```

Moreless what I'm doing is something like:

```ts
this.token = token;
this.baseUrl = baseUrl;
this.prefix = CONFIG['MATRIX_ROOM_PREFIX'];

this.client = sdk.createClient({
  baseUrl: baseUrl,
  accessToken: token,
  fetchFn: fetch
});

// @ts-ignore
this.client.on("sync", async (state, prevState, data) => {
    switch (state) {
        case "ERROR":
            // update UI to say "Connection Lost"
            break;
        case "SYNCING":
            // update UI to remove any "Connection Lost" message
            break;
        case "PREPARED":
            // the client instance is ready to be queried.
            var rooms = this.client.getRooms();
            break;
    }
});

this.client.startClient();
```
All the time the state is `ERROR` and is showing this on loop.

**Comment by t3chguy** [comment]
`createClient` needs a `userId` given to it when using the /sync API e.g. from startClient. You can use the `whoami` API to get this info from the server before calling `startClient`

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-js-sdk#examples

**Comment by selankon** [comment]
So, if I want to use the whoami API, what I should do is this?

```ts
        client = sdk.createClient({
            baseUrl: baseUrl,
            accessToken: token,
        });

        const userId = this.client.whoami()

        client = sdk.createClient({
            baseUrl: baseUrl,
            accessToken: token,
            userId: userId
        });
```

Because there is no setter for `userId` after instantiate a client. This is not really pretty. There is some better way to do this?

**Comment by t3chguy** [comment]
`const { user_id: userId } = await this.client.whoami()`

the `whoami` call is async so would need awaiting.

You could then update `client.credentials.userId = userId;` or construct a new client as you have done.

**Comment by selankon** [comment]
ok thanks again!
