### ISSUE TITLE
global.fetch is not a function

### ISSUE THREAD

**Issue by MuhChy** [matrix-org/matrix-js-sdk#2995]
Hey i updated matrix-js-sdk version and now i run into this error:

```
d:\Appz\Stuff\matrixBot\node_modules\matrix-js-sdk\lib\http-api\fetch.js:255
      throw new _errors.ConnectionError("fetch failed", e);
            ^

ConnectionError: fetch failed: global.fetch is not a function
```

Any ideas?

I already tried it with a minimal example but i run into the same problem.
Thanks for your attention.

```

const sdk = require('matrix-js-sdk');

const client = sdk.createClient({
    baseUrl: "https://mydomain.com",
    accessToken: "syt_xyz",
    userId: "@afezcoyqx2dqi22mudzgo6lokl5ongo76pswavhkvyshq77xjhmac===:mydomain.com"
});

Output:

Getting saved sync token...
Getting push rules...
Attempting to send queued to-device messages
Got saved sync token
Got reply from saved sync, exists? false
All queued to-device messages sent
Getting push rules failed ConnectionError: fetch failed: global.fetch is not a function
```

**Comment by t3chguy** [comment]
As per breaking changes https://github.com/matrix-org/matrix-js-sdk/releases/tag/v21.0.0 moves to fetch. You either need to use an environment with global fetch such as modern Web or NodeJS 18+ or install it via node-fetch, cross-fetch etc.

**Comment by MuhChy** [comment]
Hey thanks for your answer but i'm using a fresh synapse install and a fresh env with the latest nodejs and the latest matrix-js-sdk.

**Comment by MuhChy** [comment]
> As per breaking changes https://github.com/matrix-org/matrix-js-sdk/releases/tag/v21.0.0 moves to fetch. You either need to use an environment with global fetch such as modern Web or NodeJS 18+ or install it via node-fetch, cross-fetch etc.

Hey thanks for your answer but i'm using a fresh synapse install and a fresh env with the latest nodejs and the latest matrix-js-sdk.

**Comment by t3chguy** [comment]
Latest nodejs is 19, Node 18+ has global.fetch as seen here

![image](https://user-images.githubusercontent.com/2403652/208454160-5b12a268-df32-4ea2-9ef6-600d8daa3af7.png)

**Comment by MuhChy** [comment]
node -v
v18.12.1

**Comment by Half-Shot** [comment]
```
$ node
Welcome to Node.js v18.12.0.
Type ".help" for more information.
> global.fetch
[AsyncFunction: fetch]
```

Should be fine, as per @t3chguy's comment.

**Comment by MuhChy** [comment]
Ok i it was a problem with haproxy... IT stuff you know :P.
But i now run into another problem.
Do you maybe have a answer for that problem too ? :) 
Thank you.

```
Number of consecutive failed sync requests: 14
Starting keep-alive
/sync error M_UNKNOWN: MatrixError: [500] Internal server error (https://test.muhzone.de/_matrix/client/r0/sync?filter=1&timeout=0&_cacheBuster=1671484716268)
    at parseErrorResponse (d:\Appz\TS5Bot\matrixBotByAI\node_modules\matrix-js-sdk\lib\http-api\utils.js:81:12)
    at MatrixHttpApi.requestOtherUrl (d:\Appz\TS5Bot\matrixBotByAI\node_modules\matrix-js-sdk\lib\http-api\fetch.js:260:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatus: 500,
  url: 'https://test.muhzone.de/_matrix/client/r0/sync?filter=1&timeout=0&_cacheBuster=1671484716268',
  event: undefined,
  errcode: 'M_UNKNOWN',
  data: [Object]
}
```

Used code:
```
const fs = require('fs');
const sdk = require("matrix-js-sdk");

// Teststuff
const testRoom_1 = "!krhIoIVPPBkhySPxrh:test.muhzone.de"

// Load config
const config = JSON.parse(fs.readFileSync('config.json', 'utf8'));

// Create a new Matrix-Client-Instance
const client = sdk.createClient({
  baseUrl: config.matrix.domain,
  accessToken: config.matrix.accessToken,
  userId: config.matrix.userId, // The user ID of the client
});

async function sendTextMessage(message) {

  // Define message
  const content = {
    body: message,
    msgtype: "m.text",
};

// Send a message to the test room
client.sendEvent(testRoom_1, "m.room.message", content, "", (err, res) => {
    console.log(err);
});
};

async function main() {
  // startClient
	await client.startClient({ initialSyncLimit: 10 });

  // Send message to the test room
  //sendTextMessage("Python SDK-Test");

};

main();
```

**Comment by t3chguy** [comment]
You'd need to check your server logs to know what an internal server error is. Also this isn't a support channel but a bug tracker. If you need help i suggest joining #matrix-dev:matrix.org on Matrix

**Comment by austererisk** [comment]
For me, I had two issues with Vite:

1. global.fetch is not defined
2. Buffer is not defined

I fixed these with:

1. Add to _vite.config.ts_
```  
define: {
    global: "window",
  },
```
2. The instructions here [](https://techblog.inplayer.com/p/migrating-our-react-setup-to-vite)

```
npm i buffer process @rollup/plugin-inject
```

_vite.config.ts_
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import tsconfigPaths from "vite-tsconfig-paths";
import inject from "@rollup/plugin-inject";

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  define: {
    global: "window",
  },
  build: {
    rollupOptions: {
      plugins: [inject({ Buffer: ["Buffer", "Buffer"], process: "process" })],
    },
  },
});
```
_index.html_
```
<script type="module" src="/src/nodespecific.ts"></script>
```
