### ISSUE TITLE
Cannot create property 'store' on string

### ISSUE THREAD

**Issue by MauritzFunke** [matrix-org/matrix-js-sdk#3048]
Hello,
I'm trying using this sdk but its failing from the beginning.
I have set up a test project with just this sdk ("matrix-js-sdk": "^23.0.0").
My app.js looks like this

```
import * as sdk from "matrix-js-sdk";                                                                                                                                                       
const client = sdk.createClient("https://matrix.org");
```

and its already giving me this error:
```
  opts.store = (_opts$store = opts.store) !== null && _opts$store !== void 0 ? _opts$store : new _memory.MemoryStore({
             ^

TypeError: Cannot create property 'store' on string 'https://matrix.org'
    at amendClientOpts (node_modules/matrix-js-sdk/lib/matrix.js:447:14)
    at Module.createClient (node_modules/matrix-js-sdk/lib/matrix.js:466:35)
    at matrix-bot/app.js:2:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

I'm using node v18.13.0 and yarn 1.22.19

**Comment by t3chguy** [comment]
I suggest `const client = sdk.createClient({ baseUrl: "https://matrix.org/" });`

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/blob/8e29f8ead0bd0341563469ab43a6ac87ae1c39e8/src/matrix.ts#L96 takes an ICreateClientOpts not a string.
