### ISSUE TITLE
Cannot install?

### ISSUE THREAD

**Issue by ondras** [matrix-org/matrix-js-sdk#3116]
Hi,

this is my attempt at installing the dependencies on a fresh checkout:

```
~/matrix-js-sdk (git:develop) $ yarn -v
3.3.1
~/matrix-js-sdk (git:develop) $ node -v
v16.19.0
~/matrix-js-sdk (git:develop) $ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0061: │ react-frame-component@npm:5.2.5 is deprecated: Package is currently broken please use 5.2.4 for now until fix is rolled out
➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0001: │ Error: @matrix-org/olm@https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.14.tgz: @matrix-org/olm@npm:3.2.14::__archiveUrl=https%3A%2F%2Fgitlab.matrix.org%2Fapi%2Fv4%2Fprojects%2F27%2Fpackages%2Fnpm%2F%40matrix-org%2Folm%2F-%2F%40matrix-org%2Folm-3.2.14.tgz%23 isn't supported by any available resolver
    at zf.getResolverByDescriptor (/home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:391:1647)
    at zf.getCandidates (/home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:391:1235)
    at pb.getCandidates (/home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:435:3324)
    at zf.getCandidates (/home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:391:1264)
    at /home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:439:7695
    at Ff (/home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:390:8965)
    at ge (/home/ondras/.cache/node/corepack/yarn/3.3.1/yarn.js:439:7675)
➤ YN0000: └ Completed in 21s 433ms
➤ YN0000: Failed with errors in 21s 436ms
```

**Comment by t3chguy** [comment]
The readme links to Yarn Classic for a reason - https://classic.yarnpkg.com/en/docs/install

Newer yarn versions drop/change support for things like git&tar dependencies

**Comment by ondras** [comment]
I see, thanks. Perhaps the "yarn classic" could be also mentioned somewhere in the actual visible README text, as not everyone (me included) is bright enough to study where the `yarn` link leads to.
