### ISSUE TITLE
New room type breaks old SDK leading to chain of issues

### ISSUE THREAD

**Issue by davehayes** [matrix-org/matrix-js-sdk#3166]
So I had a bot using matrix-js-sdk which choked on the new room format. I updated the sdk to 23 and this happens:

```
sessionStore: new sdk.WebStorageSessionStore(localStorageSession),
                         ^
TypeError: sdk.WebStorageSessionStore is not a constructor
```

I see in various issues that WebStorageSessionStore has been somehow deprecated. That's fine, but what do we use if we -were- using that? Thanks in advance.

**Comment by t3chguy** [comment]
Just remove that line, the store only stored one field and it has been migrated elsewhere.

**Comment by davehayes** [comment]
So that didn't work. 

I used to do this:

```
const localStorageCrypto = createLocalStorage({
  mode: "node",
  storeFilePath: botDir + 'mycryptostuff'
});

const localStorageSession = createLocalStorage({
  mode: "node",
  storeFilePath: botDir + 'mysession'
});
...

const botclient = sdk.createClient({
  ...
  cryptoStore: new LocalStorageCryptoStore(localStorageCrypto),
  sessionStore: new sdk.WebStorageSessionStore(localStorageSession),
  userId: myUserId,
  useAuthorizationHeader: true
});
```

So, per your advice, I commented out the `sessionStore` line, installed 21.3 (up from what worked which was 17.2.0) using yarn and I got this:

```
Checking key backup status...
Error checking for active key backup ConnectionError: fetch failed: global.fetch is not a function
    at MatrixHttpApi.requestOtherUrl (/my/bot/code/node_modules/matrix-js-sdk/lib/http-api/fetch.js:241:13)
    at MatrixHttpApi.request (/my/bot/code/node_modules/matrix-js-sdk/lib/http-api/fetch.js:171:17)
    at MatrixHttpApi.authedRequest (/my/bot/code/node_modules/matrix-js-sdk/lib/http-api/fetch.js:129:33)
    at MatrixClient.getKeyBackupVersion (/my/bot/code/node_modules/matrix-js-sdk/lib/client.js:1952:29)
    at BackupManager.checkAndStart (/my/bot/code/node_modules/matrix-js-sdk/lib/crypto/backup.js:156:65)
    at Crypto.init (/my/bot/code/node_modules/matrix-js-sdk/lib/crypto/index.js:370:24)
    at async MatrixClient.initCrypto (/my/bot/code/node_modules/matrix-js-sdk/lib/client.js:976:5)
```

Looks like crypto has changed too, which would be painful because I have this bot in an encrypted room. How can I proceed here?
