### ISSUE TITLE
SDK not working despite Node 18 polyfill and various methods

### ISSUE THREAD

**Issue by davehayes** [matrix-org/matrix-js-sdk#3192]
Ok so I've had a matrix bot running for months. Recently,  I filed #3166 but this is really a symptom of some deeper issue.

Here is my "regenerate everything from scratch" script. 

```/bin/sh
#!/bin/sh
rm -rf node_modules package.json yarn.lock 2>&1 >/dev/null
if [ "x$1" = "xold" ] ; then
   yarn add matrix-js-sdk@18.1.0
   yarn add https://packages.matrix.org/npm/olm/olm-3.1.4.tgz
   yarn add localstorage-ponyfill
else
   yarn add matrix-js-sdk
   yarn add https://packages.matrix.org/npm/olm/olm-3.1.4.tgz
   yarn add localstorage-ponyfill
fi
```
I've been using this to test the following code

```javascript
import Olm from "olm";
import * as sdk from "matrix-js-sdk";
import { createLocalStorage } from "localstorage-ponyfill";
...
import { LocalStorageCryptoStore } from 'matrix-js-sdk/lib/crypto/store/localStorage-crypto-store.js';
global.Olm = Olm;
...
const localStorageCrypto = createLocalStorage({
  mode: "node",
  storeFilePath: botDir + 'mycryptostuff'
});

const localStorageSession = createLocalStorage({
  mode: "node",
  storeFilePath: botDir + 'mysession'
});
...

var botclient;
try {
    botclient = sdk.createClient({
      ...
      cryptoStore: new LocalStorageCryptoStore(localStorageCrypto),
      sessionStore: new sdk.WebStorageSessionStore(localStorageSession),
      ...
    });
} catch {
  console.log("Error with first method, trying 2nd");
  try {
    botclient = sdk.createClient({
      ...
      cryptoStore: new LocalStorageCryptoStore(localStorageCrypto),
      ...
    });
  } catch {
    console.log("Failed to make botclient");
    process.exit(2);
  }
}
```

So if I use the old versions (see the above `/bin/sh` script) I get this:
```
Crypto: Starting up crypto store...
...
Crypto: initialising roomlist...
Crypto: initialising crypto object...
Crypto: initialising Olm...
(node:95359) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Failed to parse URL from /Source/c3p0/node_modules/olm/olm.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at /Source/c3p0/node_modules/olm/olm.js:31:139
      at /Source/c3p0/node_modules/olm/olm.js:31:362
      at /Source/c3p0/node_modules/olm/olm.js:31:375 {
    input: '/Source/c3p0/node_modules/olm/olm.wasm',
    code: 'ERR_INVALID_URL'
```

Now if I use what is recommended on the README page for this repo (again see the `/bin/sh` script)  I get this:

```
Error with first method, trying 2nd
Crypto: Starting up crypto store...
BotCmd
Crypto: initialising roomlist...
Crypto: initialising crypto object...
Crypto: initialising Olm...
wasm streaming compile failed: TypeError: Failed to parse URL from /Source/c3p0/node_modules/olm/olm.wasm
falling back to ArrayBuffer instantiation
(node:87605) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Crypto: initialising Olm device...
ERROR:  Error: OLM.UNKNOWN_PICKLE_VERSION
    at /Source/c3p0/node_modules/olm/olm.js:89:206
    at W.<anonymous> (/Source/c3p0/node_modules/olm/olm.js:93:104)
    at W.unpickle (/Source/c3p0/node_modules/olm/olm.js:88:379)
    at /Source/c3p0/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:223:19
    at LocalStorageCryptoStore.getAccount (/Source/c3p0/node_modules/matrix-js-sdk/lib/crypto/store/localStorage-crypto-store.js:348:5)
    at /Source/c3p0/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:221:24
    at LocalStorageCryptoStore.doTxn (/Source/c3p0/node_modules/matrix-js-sdk/lib/crypto/store/localStorage-crypto-store.js:374:28)
    at OlmDevice.initialiseAccount (/Source/c3p0/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:220:28)
    at OlmDevice.init (/Source/c3p0/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:178:20)
```

I changed 3.14 to the latest I see on https://packages.matrix.org/npm/olm/ (which would be 3.2.1) and I get a bit farther (well at least I -think- it is farther):

```
Error with first method, trying 2nd
Crypto: Starting up crypto store...
BotCmd
Crypto: initialising roomlist...
Crypto: initialising crypto object...
Crypto: initialising Olm...
(node:79557) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Failed to parse URL from /Source/c3p0/node_modules/olm/olm.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at /Source/c3p0/node_modules/olm/olm.js:31:139
      at /Source/c3p0/node_modules/olm/olm.js:31:362
      at /Source/c3p0/node_modules/olm/olm.js:31:375 {
    input: '/Source/c3p0/node_modules/olm/olm.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```
So three questions:

1) What is the correct version combination for matrix-js-sdk and olm?
2) What do I have to do to recover my code from the "old way" of doing a session store?
3) How do I get this all working again? (More exactly: what is the correct way of starting the SDK and Olm together to produce a matrix client that can handle encrypted rooms?)

Thanks in advance.

**Comment by davehayes** [comment]
So I had to move back to node 16 to get my bot to work. I also had to do this:

```javascript
import fetch from 'node-fetch';
...
global.fetch = fetch;
```

Of course, I had to install node-fetch with yarn.  The questions above are still valid from me, because I'd like to move to node 18.

**Comment by t3chguy** [comment]
Update your version of Olm, it is too old for Node 18 compatibility.
