### ISSUE TITLE
Matrix hangs randomly but not crash, can send message but can't receive any message after this error came out

### ISSUE THREAD

**Issue by myfingerhurt** [matrix-org/matrix-js-sdk#635]
Here is the Error, this is annoying, I have to reboot matrix-js-sdk very single time manually.
How can I recover from this kind of errors, I would rather it could crash.

/sync error Error: Server returned 503 error
{ Error: Server returned 503 error
    at parseErrorResponse (/Bots/node_modules/matrix-js-sdk/lib/http-api.js:828:15)
    at /Bots/node_modules/matrix-js-sdk/lib/http-api.js:777:27
    at Request._callback (/Bots/node_modules/matrix-js-sdk/lib/http-api.js:727:17)
    at Request.self.callback (/Bots/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Bots/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Bots/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) httpStatus: 503 }

**Comment by turt2live** [comment]
The js-sdk should be self-healing in this error. It will keep trying to sync until it's stopped.

**Comment by turt2live** [comment]
I'm assuming due to lack of response that this isn't an issue. It looks like a server problem. If the issue is still happening, please open a new issue or visit us in [#matrix-dev:matrix.org](https://matrix.to/#/#matrix-dev:matrix.org)
